# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goblin < Formula
  desc ""
  homepage "https://github.com/kryn3n/goblin"
  version "0.1.0"

  on_macos do
    url "https://github.com/kryn3n/goblin/releases/download/v0.1.0/goblin_0.1.0_darwin_all.tar.gz"
    sha256 "5822698dfd6fdc31bdace2b9b0265b4a294c3fc4f7e19415860b15f48e855a3f"

    def install
      bin.install "goblin"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kryn3n/goblin/releases/download/v0.1.0/goblin_0.1.0_linux_amd64.tar.gz"
        sha256 "f28fbb527583c7f74531f2ad4b31062eec88b6351f6703ee92ed97f83b5e615b"

        def install
          bin.install "goblin"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kryn3n/goblin/releases/download/v0.1.0/goblin_0.1.0_linux_arm64.tar.gz"
        sha256 "d1a9e656bef637207f2a6e2c979d2fe6d07a10c68c7763f8de67f57bf54ffa4b"

        def install
          bin.install "goblin"
        end
      end
    end
  end
end
